<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;

class GiveUsersUniqueIdentifierCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:give-users-unique-identifier-command';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {

        $names = collect(array (
            0 => 'directmonitor',
            1 => 'strictdefensive',
            2 => 'colonialasian',
            3 => 'batsamend',
            4 => 'sparkept',
            5 => 'feedvirginia',
            6 => 'degreecaught',
            7 => 'zebratough',
            8 => 'wildebeestcajole',
            9 => 'admitpager',
            10 => 'kookaburrageldings',
            11 => 'kitepiglet',
            12 => 'cornettopuck',
            13 => 'reefprominent',
            14 => 'joinerlollipop',
            15 => 'castgracious',
            16 => 'profilesecretive',
            17 => 'swimsuitunwilling',
            18 => 'onerouskangaroo',
            19 => 'recklessfuttock',
            20 => 'neptunestriped',
            21 => 'mealyhushed',
            22 => 'cheerydirection',
            23 => 'meatballaloof',
            24 => 'vaporunhelpful',
            25 => 'hauntingyogurt',
            26 => 'turtleneckgrow',
            27 => 'sealbike',
            28 => 'undressskier',
            29 => 'yardarmfancy',
            30 => 'expressionpackage',
            31 => 'stoneinvent',
            32 => 'saritremendous',
            33 => 'strangerwhisper',
            34 => 'trainingnowhere',
            35 => 'soupysneering',
            36 => 'deliveractuary',
            37 => 'swimloosen',
            38 => 'leadquality',
            39 => 'signpostneck',
            40 => 'totallylayer',
            41 => 'badmintonflow',
            42 => 'skegbewitched',
            43 => 'nounsheadwaters',
            44 => 'travelflatfoot',
            45 => 'shieldteam',
            46 => 'dotterelcamera',
            47 => 'knotwildcat',
            48 => 'yuletidebroke',
            49 => 'rowboatsmelt',
            50 => 'boomerangheat',
            51 => 'confidencegrinch',
            52 => 'generatehorseman',
            53 => 'foreignregularly',
            54 => 'principaloysters',
            55 => 'theorizecowardice',
            56 => 'confesslist',
            57 => 'sobcareer',
            58 => 'justicebaron',
            59 => 'analyzecooked',
            60 => 'consensusstretch',
            61 => 'pedlarbroker',
            62 => 'traditionartist',
            63 => 'gullssolo',
            64 => 'jewelsstamp',
            65 => 'impoliterasp',
            66 => 'containjersey',
            67 => 'umbrellaunlike',
            68 => 'unhelpfulman',
            69 => 'properfall',
            70 => 'huddlediscovery',
            71 => 'vineshulking',
            72 => 'exposuresanta',
            73 => 'surprisingscaffolding',
            74 => 'bongattitude',
            75 => 'smashfeet',
            76 => 'muchexacting',
            77 => 'oysterisland',
            78 => 'flowerschemise',
            79 => 'shirtcheckup',
            80 => 'rigidstairs',
            81 => 'camouflageprancer',
            82 => 'precludeinstant',
            83 => 'delicatelie',
            84 => 'alliumrow',
            85 => 'woodperegrine',
            86 => 'thwackstream',
            87 => 'exceedhound',
            88 => 'imperfectsnappy',
            89 => 'cellulosetelephone',
            90 => 'asterngusty',
            91 => 'meatcell',
            92 => 'spindlesaid',
            93 => 'rubcrease',
            94 => 'microwavepunctual',
            95 => 'inventcope',
            96 => 'revenuespider',
            97 => 'kraftmyth',
            98 => 'wholepoll',
            99 => 'proficientjumbled',
            100 => 'fanfarepartial',
            101 => 'sowdepressed',
            102 => 'suddenlyassault',
            103 => 'evanescentsecret',
            104 => 'netherextrasmall',
            105 => 'trafalgargleaming',
            106 => 'tangyanguished',
            107 => 'awaywither',
            108 => 'dyeforce',
            109 => 'honestportly',
            110 => 'moroseboundary',
            111 => 'writheera',
            112 => 'zulubrails',
            113 => 'curlingcowardly',
            114 => 'chemisediscipline',
            115 => 'ponchosniff',
            116 => 'knobexperience',
            117 => 'mongooseski',
            118 => 'milliontalent',
            119 => 'compromiseswan',
            120 => 'generositybandanna',
            121 => 'guillemotsbank',
            122 => 'oafishevasive',
            123 => 'flockflamboyant',
            124 => 'lexussway',
            125 => 'housestaid',
            126 => 'homesadhoc',
            127 => 'dangoshout',
            128 => 'buzzingcowboy',
            129 => 'skeletonwasteful',
            130 => 'oreganounable',
            131 => 'scratchyuncut',
            132 => 'bongowebbed',
            133 => 'tradepleasing',
            134 => 'melonshysterical',
            135 => 'tonemade',
            136 => 'japanpuzzled',
            137 => 'founderrecommend',
            138 => 'ministerhandiwork',
            139 => 'fishermanarrogant',
            140 => 'withwere',
            141 => 'fabriclappet',
            142 => 'adoringpolarbear',
            143 => 'speckledearing',
            144 => 'ambiguousobstinacy',
            145 => 'rubberynew',
            146 => 'brokenrepulsive',
            147 => 'unwieldyvelvety',
            148 => 'devilishdisruptive',
            149 => 'unsungbeneficent',
            150 => 'costlymemorize',
            151 => 'teachingseabird',
            152 => 'lovelilypad',
            153 => 'buzzardsociable',
            154 => 'attachstay',
            155 => 'mooshroomgym',
            156 => 'dolphinsomewhat',
            157 => 'rewardlucky',
            158 => 'hebrewobsidian',
            159 => 'gorgeoussoda',
            160 => 'vaulterogle',
            161 => 'lizardporsche',
            162 => 'xebecwipe',
            163 => 'polecatsanalyst',
            164 => 'savingshastiness',
            165 => 'regionalbikini',
            166 => 'muralgoofy',
            167 => 'phonycup',
            168 => 'currentanyway',
            169 => 'belthoneycomb',
            170 => 'grovewrite',
            171 => 'northerlyjib',
            172 => 'gaffsecondhand',
            173 => 'currycumbersome',
            174 => 'guineafowlrevolution',
            175 => 'fillfire',
            176 => 'applicantfantasy',
            177 => 'weighpurple',
            178 => 'richessejelly',
            179 => 'mueslidetector',
            180 => 'brassierejoyful',
            181 => 'rhinoaboard',
            182 => 'boatupshot',
            183 => 'barrensvisa',
            184 => 'creepydosage',
            185 => 'dopeyglowstone',
            186 => 'punishmentmine',
            187 => 'cuckoothank',
            188 => 'editreflecting',
            189 => 'grousestripe',
            190 => 'deservespurious',
            191 => 'forestersnapshot',
            192 => 'followingfiber',
            193 => 'gleandug',
            194 => 'teenburden',
            195 => 'inactiveorder',
            196 => 'bookshelfgroup',
            197 => 'concludeskeleton',
            198 => 'wicketmojang',
            199 => 'hamiltondeny',
        ));


        User::all()->each(function ($user) use ($names) {
            $user->identifier = rand(1000,9999);
            $user->username = $names->random();
            $user->save();
        });
    }
}
